apiVersion: v1
kind: Service
metadata:
  name: myweb-service
spec:
  type: NodePort
  selector:
    app: myweb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  
